spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:agentdb
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
api:
 security:
    token:
        secret: ${JWT_SECRET:my-secret-key}

user:
    mock:
        username: admin@admin.com
        password: Senha12345

server:
  port: 8080